name: CI/CD for Snowflake Glue Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Lint with pylint
        run: |
          pylint src/glue_snowflake_pipeline.py

      - name: Run tests
        run: |
          pytest tests/test_pipeline.py

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy script to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws s3 cp src/glue_snowflake_pipeline.py s3://your-bucket/scripts/

      - name: Deploy Glue job
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws glue create-job --cli-input-json file://config/glue_job_config.json || aws glue update-job --cli-input-json file://config/glue_job_config.json